### ISSUE TITLE
UI(User Interface) Issues

### ISSUE THREAD

**Issue by Ghamees** [msaaddev/CS311S20PID43#19]
1.	There should be scroll up and down option in the table view section
2.	There can be an edit option button to edit the table 
3.	There should be a little description of teacher name with their related subjects in the final generated table

**Comment by msaaddev** [comment]
Fixed no. `3` in c974ce9.

**Comment by msaaddev** [comment]
Fixed no. 1 in 714c144. The height of the `.sh_subcontainer_timetable` class is relative now so it will adjust according to the content.

![image](https://user-images.githubusercontent.com/44341551/90003581-b7d71300-dcad-11ea-808f-72e0508b71c6.png)

**Comment by msaaddev** [comment]
We can't provide the no. 2 suggestion since then there will be no purpose of writing an algorithm then if we are going to change the schedule.

**Comment by msaaddev** [comment]
Closing this issue.
