### ISSUE TITLE
Table Creation Issues

### ISSUE THREAD

**Issue by Ghamees** [msaaddev/CS311S20PID43#20]
1.	When pressing “clear” it deletes the whole table but doesn’t allow to clear or edit the one row or some specific data only. 
2.	With same course ID and same section you can add two teachers to teach on the section with the same subject which is not possible, but it does take the first one only in the final generates the table, preference vise is good, but there should be a restriction on this or a warning.
3.	Course ID option doesn’t add any alphabetic character like “CS-311” It only adds numeric values like “311”.
4.	Room numbers, sessions, sections are limited. Only those are available which are given in the drop-down selection. There could be more but it’s a good table for the 18-session only.

**Comment by msaaddev** [comment]
Fixed no. 2 in 4201a4f.

![image](https://user-images.githubusercontent.com/44341551/90004406-089b3b80-dcaf-11ea-8f61-b367c030b70f.png)

**Comment by msaaddev** [comment]
No. 3 and 4 do not fall in the project scope.

**Comment by msaaddev** [comment]
Closing this issue.
